name: Create EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  create-ec2-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Change to your desired region

    - name: Launch EC2 Instance
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ami-0c55b159cbfafe1f0 \  # Update with your preferred AMI ID
          --count 1 \
          --instance-type t2.micro \  # Update with your preferred instance type
          --key-name my-key-pair \  # Update with your key pair name
          --security-group-ids sg-0bb1c23b6eEXAMPLE \  # Update with your security group ID
          --subnet-id subnet-6e7f829e \  # Update with your subnet ID
          --query 'Instances[0].InstanceId' \
          --output text)

        echo "EC2 Instance ID: $INSTANCE_ID"

    - name: Wait for EC2 Instance to be running
      run: |
        aws ec2 wait instance-running --instance-ids $INSTANCE_ID
        echo "EC2 Instance $INSTANCE_ID is running"

    - name: Describe EC2 Instance
      run: |
        aws ec2 describe-instances --instance-ids $INSTANCE_ID
